
language: cpp
sudo: false
dist: trusty
matrix:
   fast_finish: true
   include:
      - os: linux
      addons: &1
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
            - gcc-7
      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"
        - CMAKE_VERSION="3.9.2"
        - BUILDFLAGS="VERBOSE=1"

script:
   - ./tests/test_TestDrivenDevbyExample  "TDDbyexample test"

notifications:
   email: false
